type RelayWebForward = {
  publicPort: number;
  targetPort: number;
  tunnelIp: string;
  relayHost: string;
};


const DOMAIN = /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;


function relayForwardServer(forward: RelayWebForward): string {
  return (
    `server {\n` +
    `  listen ${forward.publicPort} ssl;\n` +
    `  server_name ${forward.relayHost};\n` +
    `  ssl_certificate     /etc/nginx/certs/wildcard.crt;\n` +
    `  ssl_certificate_key /etc/nginx/certs/wildcard.key;\n` +
    `  error_page 502 503 504 =503 /offline-${forward.publicPort}.html;\n` +
    `  location = /offline-${forward.publicPort}.html {\n` +
    `    root /etc/nginx/slh-errors;\n` +
    `    internal;\n` +
    `  }\n` +
    `  location / {\n` +
    `    proxy_pass http://${forward.tunnelIp}:${forward.targetPort};\n` +
    `    proxy_set_header Host $host;\n` +
    `    proxy_http_version 1.1;\n` +
    `    proxy_intercept_errors on;\n` +
    `    proxy_connect_timeout 5s;\n` +
    `  }\n` +
    `}`
  );
}

/** Builds the nginx include consumed by the relay's existing sync script. */
export function buildRelayNginxConfig(input: { webForwards: RelayWebForward[] }): string {
  const seenPorts = new Set<number>();
  const forwards = input.webForwards
    .filter((forward) => {
      if (seenPorts.has(forward.publicPort)) return false;
      seenPorts.add(forward.publicPort);
      return true;
    })
    .map(relayForwardServer);
  /* Les instances MikHmon cloud ne sont PLUS servies ici : Traefik détient
     443 sur le relais et porte déjà le certificat joker. Émettre un
     `listen 443` faisait échouer `nginx -t`, donc refuser le rechargement du
     fichier ENTIER — toutes les redirections gelaient avec lui. */
  return `# Auto-generated by SafeLinkHub (relay-nginx). Do not edit.\n${forwards.join("\n")}\n`;
}
