type RelayWebForward = {
  publicPort: number;
  targetPort: number;
  tunnelIp: string;
  relayHost: string;
};

type CloudInstance = {
  domain: string;
  localPort: number;
  status: string;
};

const DOMAIN = /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;

function cloudServer(instance: CloudInstance): string {
  if (!DOMAIN.test(instance.domain)) {
    throw new Error("Cloud MikHmon instance has an invalid domain.");
  }
  if (!Number.isInteger(instance.localPort) || instance.localPort < 20_000 || instance.localPort > 20_999) {
    throw new Error("Cloud MikHmon instance has an invalid private port.");
  }
  return (
    `server {\n` +
    `  listen 443 ssl;\n` +
    `  server_name ${instance.domain};\n` +
    `  ssl_certificate     /etc/nginx/certs/mikhmon-cloud-wildcard.crt;\n` +
    `  ssl_certificate_key /etc/nginx/certs/mikhmon-cloud-wildcard.key;\n` +
    `  location / {\n` +
    `    proxy_pass http://127.0.0.1:${instance.localPort};\n` +
    `    proxy_set_header Host $host;\n` +
    `    proxy_set_header X-Forwarded-Proto https;\n` +
    `    proxy_http_version 1.1;\n` +
    `    proxy_connect_timeout 5s;\n` +
    `  }\n` +
    `}`
  );
}

function relayForwardServer(forward: RelayWebForward): string {
  return (
    `server {\n` +
    `  listen ${forward.publicPort} ssl;\n` +
    `  server_name ${forward.relayHost};\n` +
    `  ssl_certificate     /etc/nginx/certs/wildcard.crt;\n` +
    `  ssl_certificate_key /etc/nginx/certs/wildcard.key;\n` +
    `  error_page 502 503 504 =503 /offline-${forward.publicPort}.html;\n` +
    `  location = /offline-${forward.publicPort}.html {\n` +
    `    root /etc/nginx/slh-errors;\n` +
    `    internal;\n` +
    `  }\n` +
    `  location / {\n` +
    `    proxy_pass http://${forward.tunnelIp}:${forward.targetPort};\n` +
    `    proxy_set_header Host $host;\n` +
    `    proxy_http_version 1.1;\n` +
    `    proxy_intercept_errors on;\n` +
    `    proxy_connect_timeout 5s;\n` +
    `  }\n` +
    `}`
  );
}

/** Builds the nginx include consumed by the relay's existing sync script. */
export function buildRelayNginxConfig(input: {
  webForwards: RelayWebForward[];
  cloudInstances: CloudInstance[];
}): string {
  const seenPorts = new Set<number>();
  const forwards = input.webForwards
    .filter((forward) => {
      if (seenPorts.has(forward.publicPort)) return false;
      seenPorts.add(forward.publicPort);
      return true;
    })
    .map(relayForwardServer);
  const clouds = input.cloudInstances
    .filter((instance) => instance.status === "active")
    .map(cloudServer);
  return `# Auto-generated by SafeLinkHub (relay-nginx). Do not edit.\n${[...forwards, ...clouds].join("\n")}\n`;
}
