import type { AuthDictionary } from "./index";

export const authEn: AuthDictionary = {
  shell: { metrics: ["remote services", "monitoring", "card required"] },
  login: {
    eyebrow: "Secure area", titleStart: "Take control of your ", titleMark: "network.", description: "Sign in to the dashboard that runs your routers, sales, VPN access and field operations.", footerStart: "Don't have an account?", footerLink: "Sign up", section: "Sign in", heading: "Dashboard access", lead: "Your sessions stay protected with MFA verification when it is enabled.", mfaNotice: "Enter the 6-digit code from your authenticator app.", mfaLabel: "Verification code", mfaPlaceholder: "123456 or a recovery code", mfaPending: "Verifying...", mfaSubmit: "Verify", resendPromptStart: "Send the activation link again to", resendPromptEnd: "?", email: "Email", emailPlaceholder: "john.doe@example.com", password: "Password", forgot: "Forgot password?", pending: "Signing in...", submit: "Sign in",
  },
  register: {
    eyebrow: "Free account", titleStart: "Launch your ", titleMark: "hotspot portal.", description: "Create an account to manage sales, MikroTik routers, direct access and subscriptions from one interface.", footerStart: "Already have an account?", footerLink: "Sign in", section: "Sign up", heading: "Create a SafeLinkHub account", lead: "Your account starts free, with no card required.", invitedByStart: "You were invited by", invitedByEnd: ".", referralStart: "Referral code", referralEnd: "— it will be checked when your account is created.", name: "Full name", namePlaceholder: "John Doe", email: "Email", emailPlaceholder: "john.doe@example.com", password: "Password", hidePassword: "Hide password", showPassword: "Show password", confirmPassword: "Confirm password", passwordsMatch: "Passwords match.", passwordsMismatch: "Passwords do not match.", accountType: "Account type", user: "User", userDetail: "One or two MikroTiks a year. Public installation pricing, nothing to pay when signing up.", reseller: "Technician or reseller", resellerDetail: "Several MikroTiks a month.", resellerPayment: "Payment is requested right after the account is created.", country: "Country of residence", phone: "Phone number", phoneCode: "Phone country code", phonePlaceholder: "07 00 00 00 00", whatsappSame: "My WhatsApp number is the same as above", whatsappPlaceholder: "WhatsApp number (with country code)", telegramSame: "My Telegram number is the same as above", telegramPlaceholder: "Telegram number (with country code)", pending: "Creating account...", submit: "Sign up", passwordExample: "At least 8 varied characters",
  },
  activation: {
    eyebrow: "Account activation", titleStart: "Activate your ", titleMark: "account.", description: "Confirm your email address to unlock access to your SafeLinkHub dashboard.", footerStart: "Need help?", footerLink: "Contact us", section: "Final step", heading: "Confirm my email", invalid: "Invalid activation link.", invalidExpired: "This activation link is invalid or has expired.", resendPrompt: "Send yourself another activation link:", backLogin: "Back to sign in", pending: "Activating your account, please wait…", ready: "Click below to confirm your address and activate your account.", pendingButton: "Activating…", submit: "Activate my account",
  },
  activationSent: {
    eyebrow: "Email verification", titleStart: "Confirm your ", titleMark: "address.", description: "One last step: verify your email to activate your account and access the dashboard.", footerStart: "Already activated?", footerLink: "Sign in", section: "Email sent", heading: "Check your inbox", sentStart: "We sent an activation link", sentTo: "to", sentEnd: ". Click it to activate your account. The link expires in 24 hours.", missing: "Nothing received? Check your spam folder, or send the link again:",
  },
  forgot: {
    eyebrow: "Secure area", titleStart: "Recover your ", titleMark: "access.", description: "Enter your account email and we will send you a link to set a new password.", footerStart: "Remember your password?", footerLink: "Sign in", section: "Forgot password", heading: "Reset your password", lead: "A secure link, valid for 1 hour, will be sent to your email address.", success: "If an account is associated with this email, a password reset link has been sent. Check your inbox and spam folder. The link expires in 1 hour.", email: "Email", placeholder: "john.doe@example.com", pending: "Sending...", submit: "Send password reset link",
  },
  reset: {
    eyebrow: "Secure area", titleStart: "Choose a new ", titleMark: "password.", description: "Set a strong password to secure your SafeLinkHub account.", footerStart: "Back to", footerLink: "sign in", section: "Password reset", heading: "New password", lead: "At least 8 characters. Choose one you do not use elsewhere.", success: "Your password has been reset. You can now sign in.", goLogin: "Go to sign in", invalid: "Invalid password reset link.", retry: "Make another request", password: "New password", confirmPassword: "Confirm password", hidePassword: "Hide password", showPassword: "Show password", passwordsMatch: "Passwords match.", passwordsMismatch: "Passwords do not match.", pending: "Resetting...", submit: "Reset password",
  },
  resend: { success: "If an unverified account matches this email, a new activation link has been sent.", email: "Email", placeholder: "john.doe@example.com", pending: "Sending...", submit: "Resend activation email" },
};
