export const authFr = {
  shell: { metrics: ["accès distants", "supervision", "carte requise"] },
  login: {
    eyebrow: "Espace sécurisé", titleStart: "Reprendre le contrôle de votre ", titleMark: "réseau.", description: "Connectez-vous au tableau de bord qui pilote vos routeurs, ventes, accès VPN et opérations terrain.", footerStart: "Vous n'avez pas de compte ?", footerLink: "Inscrivez-vous", section: "Connexion", heading: "Accès au dashboard", lead: "Vos sessions restent protégées avec vérification MFA si elle est activée.", mfaNotice: "Entrez le code à 6 chiffres de votre application d'authentification.", mfaLabel: "Code de vérification", mfaPlaceholder: "123456 ou un code de récupération", mfaPending: "Vérification...", mfaSubmit: "Vérifier", resendPromptStart: "Renvoyer le lien d'activation à", resendPromptEnd: "?", email: "Email", emailPlaceholder: "jean.dupont@exemple.com", password: "Mot de passe", forgot: "Mot de passe oublié ?", pending: "Connexion en cours...", submit: "Connexion",
  },
  register: {
    eyebrow: "Création gratuite", titleStart: "Lancer votre portail ", titleMark: "hotspot.", description: "Créez un compte pour gérer les ventes, routeurs MikroTik, accès directs et abonnements depuis une interface unifiée.", footerStart: "Vous avez déjà un compte ?", footerLink: "Connexion", section: "Inscription", heading: "Créer un compte SafeLinkHub", lead: "Le compte démarre gratuitement, sans carte bancaire.", invitedByStart: "Vous avez été invité par", invitedByEnd: ".", referralStart: "Code de parrainage", referralEnd: "— il sera vérifié à la création du compte.", name: "Nom complet", namePlaceholder: "Jean Dupont", email: "Email", emailPlaceholder: "jean.dupont@exemple.com", password: "Mot de passe", hidePassword: "Masquer le mot de passe", showPassword: "Afficher le mot de passe", confirmPassword: "Confirmez le mot de passe", passwordsMatch: "Les mots de passe correspondent.", passwordsMismatch: "Les mots de passe ne correspondent pas.", accountType: "Type de compte", user: "Utilisateur", userDetail: "Un ou deux MikroTik par an. Tarif d'installation public, rien à payer à l'inscription.", reseller: "Technicien ou revendeur", resellerDetail: "Plusieurs MikroTik par mois.", resellerPayment: "Le paiement est demandé juste après la création du compte.", country: "Pays de résidence", phone: "Numéro de téléphone", phoneCode: "Indicatif téléphonique", phonePlaceholder: "07 00 00 00 00", whatsappSame: "Mon numéro WhatsApp est le même que ci-dessus", whatsappPlaceholder: "Numéro WhatsApp (avec indicatif)", telegramSame: "Mon numéro Telegram est le même que ci-dessus", telegramPlaceholder: "Numéro Telegram (avec indicatif)", pending: "Création du compte...", submit: "S'inscrire", passwordExample: "Au moins 8 caractères, varié",
  },
  activation: {
    eyebrow: "Activation du compte", titleStart: "Activez votre ", titleMark: "compte.", description: "Confirmez votre adresse email pour débloquer l'accès à votre tableau de bord SafeLinkHub.", footerStart: "Besoin d'aide ?", footerLink: "Contactez-nous", section: "Dernière étape", heading: "Confirmer mon email", invalid: "Lien d'activation invalide.", invalidExpired: "Ce lien d'activation est invalide ou expiré.", resendPrompt: "Renvoyez-vous un lien d'activation :", backLogin: "Retour à la connexion", pending: "Activation de votre compte en cours, merci de patienter…", ready: "Cliquez ci-dessous pour confirmer votre adresse et activer votre compte.", pendingButton: "Activation en cours…", submit: "Activer mon compte",
  },
  activationSent: {
    eyebrow: "Vérification email", titleStart: "Confirmez votre ", titleMark: "adresse.", description: "Une dernière étape : validez votre email pour activer votre compte et accéder au tableau de bord.", footerStart: "Déjà activé ?", footerLink: "Connexion", section: "Email envoyé", heading: "Vérifiez votre boîte mail", sentStart: "Nous avons envoyé un lien d'activation", sentTo: "à", sentEnd: ". Cliquez dessus pour activer votre compte. Le lien expire dans 24 heures.", missing: "Rien reçu ? Vérifiez vos spams, ou renvoyez le lien :",
  },
  forgot: {
    eyebrow: "Espace sécurisé", titleStart: "Récupérez votre ", titleMark: "accès.", description: "Saisissez l'email de votre compte : nous vous enverrons un lien pour définir un nouveau mot de passe.", footerStart: "Vous vous souvenez de votre mot de passe ?", footerLink: "Connexion", section: "Mot de passe oublié", heading: "Réinitialiser le mot de passe", lead: "Un lien sécurisé, valable 1 heure, sera envoyé à votre adresse email.", success: "Si un compte est associé à cet email, un lien de réinitialisation vient d'y être envoyé. Vérifiez votre boîte mail (et vos spams). Le lien expire dans 1 heure.", email: "Email", placeholder: "jean.dupont@exemple.com", pending: "Envoi...", submit: "Envoyer le lien de réinitialisation",
  },
  reset: {
    eyebrow: "Espace sécurisé", titleStart: "Choisissez un nouveau ", titleMark: "mot de passe.", description: "Définissez un mot de passe fort pour sécuriser votre compte SafeLinkHub.", footerStart: "Retour à la", footerLink: "connexion", section: "Réinitialisation", heading: "Nouveau mot de passe", lead: "Au moins 8 caractères. Choisissez-en un que vous n'utilisez pas ailleurs.", success: "Votre mot de passe a été réinitialisé. Vous pouvez maintenant vous connecter.", goLogin: "Aller à la connexion", invalid: "Lien de réinitialisation invalide.", retry: "Refaire une demande", password: "Nouveau mot de passe", confirmPassword: "Confirmez le mot de passe", hidePassword: "Masquer le mot de passe", showPassword: "Afficher le mot de passe", passwordsMatch: "Les mots de passe correspondent.", passwordsMismatch: "Les mots de passe ne correspondent pas.", pending: "Réinitialisation...", submit: "Réinitialiser le mot de passe",
  },
  resend: { success: "Si un compte non activé correspond à cet email, un nouveau lien d'activation vient d'être envoyé.", email: "Email", placeholder: "jean.dupont@exemple.com", pending: "Envoi...", submit: "Renvoyer l'email d'activation" },
} as const;
