export type Country = { name: string; iso2: string; dialCode: string };

// West/Central African markets first (primary user base for this hotspot
// SaaS), then the rest of Africa, then a broad global tail so no real
// signup is blocked by a missing country.
export const COUNTRIES: Country[] = [
  { name: "Côte d'Ivoire", iso2: "CI", dialCode: "+225" },
  { name: "Sénégal", iso2: "SN", dialCode: "+221" },
  { name: "Mali", iso2: "ML", dialCode: "+223" },
  { name: "Burkina Faso", iso2: "BF", dialCode: "+226" },
  { name: "Bénin", iso2: "BJ", dialCode: "+229" },
  { name: "Togo", iso2: "TG", dialCode: "+228" },
  { name: "Niger", iso2: "NE", dialCode: "+227" },
  { name: "Guinée", iso2: "GN", dialCode: "+224" },
  { name: "Ghana", iso2: "GH", dialCode: "+233" },
  { name: "Nigeria", iso2: "NG", dialCode: "+234" },
  { name: "Cameroun", iso2: "CM", dialCode: "+237" },
  { name: "Gabon", iso2: "GA", dialCode: "+241" },
  { name: "Congo (Rép.)", iso2: "CG", dialCode: "+242" },
  { name: "Congo (RDC)", iso2: "CD", dialCode: "+243" },
  { name: "Tchad", iso2: "TD", dialCode: "+235" },
  { name: "République centrafricaine", iso2: "CF", dialCode: "+236" },
  { name: "Mauritanie", iso2: "MR", dialCode: "+222" },
  { name: "Guinée-Bissau", iso2: "GW", dialCode: "+245" },
  { name: "Sierra Leone", iso2: "SL", dialCode: "+232" },
  { name: "Liberia", iso2: "LR", dialCode: "+231" },
  { name: "Maroc", iso2: "MA", dialCode: "+212" },
  { name: "Algérie", iso2: "DZ", dialCode: "+213" },
  { name: "Tunisie", iso2: "TN", dialCode: "+216" },
  { name: "Égypte", iso2: "EG", dialCode: "+20" },
  { name: "Kenya", iso2: "KE", dialCode: "+254" },
  { name: "Tanzanie", iso2: "TZ", dialCode: "+255" },
  { name: "Ouganda", iso2: "UG", dialCode: "+256" },
  { name: "Rwanda", iso2: "RW", dialCode: "+250" },
  { name: "Éthiopie", iso2: "ET", dialCode: "+251" },
  { name: "Afrique du Sud", iso2: "ZA", dialCode: "+27" },
  { name: "Zambie", iso2: "ZM", dialCode: "+260" },
  { name: "Zimbabwe", iso2: "ZW", dialCode: "+263" },
  { name: "Mozambique", iso2: "MZ", dialCode: "+258" },
  { name: "Madagascar", iso2: "MG", dialCode: "+261" },
  { name: "France", iso2: "FR", dialCode: "+33" },
  { name: "Belgique", iso2: "BE", dialCode: "+32" },
  { name: "Suisse", iso2: "CH", dialCode: "+41" },
  { name: "Canada", iso2: "CA", dialCode: "+1" },
  { name: "États-Unis", iso2: "US", dialCode: "+1" },
  { name: "Royaume-Uni", iso2: "GB", dialCode: "+44" },
  { name: "Allemagne", iso2: "DE", dialCode: "+49" },
  { name: "Espagne", iso2: "ES", dialCode: "+34" },
  { name: "Portugal", iso2: "PT", dialCode: "+351" },
  { name: "Italie", iso2: "IT", dialCode: "+39" },
  { name: "Pays-Bas", iso2: "NL", dialCode: "+31" },
  { name: "Inde", iso2: "IN", dialCode: "+91" },
  { name: "Chine", iso2: "CN", dialCode: "+86" },
  { name: "Émirats arabes unis", iso2: "AE", dialCode: "+971" },
  { name: "Arabie saoudite", iso2: "SA", dialCode: "+966" },
  { name: "Brésil", iso2: "BR", dialCode: "+55" },
  { name: "Autre", iso2: "XX", dialCode: "+" },
];

export function findCountry(iso2: string): Country | undefined {
  return COUNTRIES.find((c) => c.iso2 === iso2);
}
