import { NextRequest } from "next/server";
import { eq } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { routers, routerPortForwards } from "@/lib/db/schema";
import { getRelayPublicHost } from "@/lib/mikrotik/relay";
import { isWebAccessService } from "@/lib/mikrotik/remote-access-host";

export const dynamic = "force-dynamic";

/**
 * Emits the nginx config that TLS-terminates every active browser-access
 * forward (WebFig/MikHmon) on its public port and proxies to the router's
 * tunnel IP. A systemd timer on the relay curls this, writes
 * /etc/nginx/conf.d/slh-forwards.conf and reloads nginx, so new forwards start
 * serving HTTPS without any manual step. WinBox/SSH are untouched (raw DNAT).
 */
export async function GET(request: NextRequest) {
  if (request.headers.get("authorization") !== `Bearer ${process.env.CRON_SECRET}`) {
    return new Response("Unauthorized", { status: 401 });
  }

  const db = getDb();
  const rows = await db
    .select({
      service: routerPortForwards.service,
      tunnelIp: routerPortForwards.tunnelIp,
      targetPort: routerPortForwards.targetPort,
      publicPort: routerPortForwards.publicPort,
      shard: routers.relayShard,
    })
    .from(routerPortForwards)
    .innerJoin(routers, eq(routerPortForwards.routerId, routers.id))
    .where(eq(routerPortForwards.status, "active"));

  const web = rows.filter((r) => isWebAccessService(r.service) && r.tunnelIp);
  const seenPorts = new Set<number>();
  const blocks: string[] = [];
  for (const r of web) {
    if (seenPorts.has(r.publicPort)) continue;
    seenPorts.add(r.publicPort);
    blocks.push(
      `server {\n` +
        `  listen ${r.publicPort} ssl;\n` +
        `  server_name ${getRelayPublicHost(r.shard)};\n` +
        `  ssl_certificate     /etc/nginx/certs/wildcard.crt;\n` +
        `  ssl_certificate_key /etc/nginx/certs/wildcard.key;\n` +
        // Quand le routeur est hors ligne, son tunnel ne répond pas et le
        // proxy_pass renvoie 502/504. Sans ceci l'utilisateur voit le « 502 Bad
        // Gateway » brut de nginx (déroutant : on dirait une panne du site). On
        // sert à la place une page « routeur hors ligne » PAR PORT
        // (offline-<port>.html) : le script relais (slh-nginx-sync.sh) la
        // (re)génère avec l'heure de dernière connexion du routeur (last_sync_at)
        // pour afficher « hors ligne depuis X ». Le tunnel se rétablit tout seul
        // au retour du routeur — donc pas de status 200 trompeur : on garde 503.
        `  error_page 502 503 504 =503 /offline-${r.publicPort}.html;\n` +
        `  location = /offline-${r.publicPort}.html {\n` +
        `    root /etc/nginx/slh-errors;\n` +
        `    internal;\n` +
        `  }\n` +
        `  location / {\n` +
        `    proxy_pass http://${r.tunnelIp}:${r.targetPort};\n` +
        `    proxy_set_header Host $host;\n` +
        `    proxy_http_version 1.1;\n` +
        `    proxy_intercept_errors on;\n` +
        // Un pair WireGuard hors ligne n'envoie pas de RST : le SYN part dans le
        // vide et sans ceci nginx attend proxy_connect_timeout (60s par défaut)
        // avant le 504 — l'utilisateur verrait un long blanc. 5s => la page
        // "routeur hors ligne" s'affiche vite.
        `    proxy_connect_timeout 5s;\n` +
        `  }\n` +
        `}`,
    );
  }

  const conf = `# Auto-generated by SafeLinkHub (relay-nginx). Do not edit.\n${blocks.join("\n")}\n`;
  return new Response(conf, { headers: { "content-type": "text/plain" } });
}
